/** Idiomas que Meta acepta para plantillas de WhatsApp (código → nombre). Las variantes de
 * español van en su propio grupo porque son las que usan casi todos los clientes. */
export const SPANISH_TEMPLATE_LANGUAGES = [
  { code: "es_CO", label: "Español (Colombia)" },
  { code: "es", label: "Español" },
  { code: "es_MX", label: "Español (México)" },
  { code: "es_AR", label: "Español (Argentina)" },
  { code: "es_CL", label: "Español (Chile)" },
  { code: "es_CR", label: "Español (Costa Rica)" },
  { code: "es_DO", label: "Español (República Dominicana)" },
  { code: "es_EC", label: "Español (Ecuador)" },
  { code: "es_ES", label: "Español (España)" },
  { code: "es_HN", label: "Español (Honduras)" },
  { code: "es_PA", label: "Español (Panamá)" },
  { code: "es_PE", label: "Español (Perú)" },
  { code: "es_UY", label: "Español (Uruguay)" },
] as const;

export const OTHER_TEMPLATE_LANGUAGES = [
  { code: "af", label: "Afrikáans" },
  { code: "sq", label: "Albanés" },
  { code: "de", label: "Alemán" },
  { code: "de_AT", label: "Alemán (Austria)" },
  { code: "de_CH", label: "Alemán (Suiza)" },
  { code: "ar", label: "Árabe" },
  { code: "ar_EG", label: "Árabe (Egipto)" },
  { code: "ar_AE", label: "Árabe (Emiratos Árabes Unidos)" },
  { code: "ar_LB", label: "Árabe (Líbano)" },
  { code: "ar_MA", label: "Árabe (Marruecos)" },
  { code: "ar_QA", label: "Árabe (Catar)" },
  { code: "az", label: "Azerí" },
  { code: "be_BY", label: "Bielorruso" },
  { code: "bn", label: "Bengalí" },
  { code: "bn_IN", label: "Bengalí (India)" },
  { code: "bg", label: "Búlgaro" },
  { code: "ca", label: "Catalán" },
  { code: "cs", label: "Checo" },
  { code: "zh_CN", label: "Chino (China)" },
  { code: "zh_HK", label: "Chino (Hong Kong)" },
  { code: "zh_TW", label: "Chino (Taiwán)" },
  { code: "si_LK", label: "Cingalés" },
  { code: "ko", label: "Coreano" },
  { code: "hr", label: "Croata" },
  { code: "da", label: "Danés" },
  { code: "prs_AF", label: "Darí" },
  { code: "sk", label: "Eslovaco" },
  { code: "sl", label: "Esloveno" },
  { code: "et", label: "Estonio" },
  { code: "fil", label: "Filipino" },
  { code: "fi", label: "Finés" },
  { code: "fr", label: "Francés" },
  { code: "fr_BE", label: "Francés (Bélgica)" },
  { code: "fr_CA", label: "Francés (Canadá)" },
  { code: "fr_CI", label: "Francés (Costa de Marfil)" },
  { code: "fr_MA", label: "Francés (Marruecos)" },
  { code: "fr_CH", label: "Francés (Suiza)" },
  { code: "ka", label: "Georgiano" },
  { code: "el", label: "Griego" },
  { code: "gu", label: "Guyaratí" },
  { code: "ha", label: "Hausa" },
  { code: "he", label: "Hebreo" },
  { code: "hi", label: "Hindi" },
  { code: "hu", label: "Húngaro" },
  { code: "id", label: "Indonesio" },
  { code: "en", label: "Inglés" },
  { code: "en_AU", label: "Inglés (Australia)" },
  { code: "en_CA", label: "Inglés (Canadá)" },
  { code: "en_AE", label: "Inglés (Emiratos Árabes Unidos)" },
  { code: "en_US", label: "Inglés (Estados Unidos)" },
  { code: "en_GH", label: "Inglés (Ghana)" },
  { code: "en_IN", label: "Inglés (India)" },
  { code: "en_IE", label: "Inglés (Irlanda)" },
  { code: "en_JM", label: "Inglés (Jamaica)" },
  { code: "en_MY", label: "Inglés (Malasia)" },
  { code: "en_NZ", label: "Inglés (Nueva Zelanda)" },
  { code: "en_QA", label: "Inglés (Catar)" },
  { code: "en_GB", label: "Inglés (Reino Unido)" },
  { code: "en_SG", label: "Inglés (Singapur)" },
  { code: "en_ZA", label: "Inglés (Sudáfrica)" },
  { code: "en_UG", label: "Inglés (Uganda)" },
  { code: "ga", label: "Irlandés" },
  { code: "it", label: "Italiano" },
  { code: "ja", label: "Japonés" },
  { code: "kn", label: "Canarés" },
  { code: "kk", label: "Kazajo" },
  { code: "rw_RW", label: "Kinyarwanda" },
  { code: "ky_KG", label: "Kirguís" },
  { code: "lo", label: "Lao" },
  { code: "lv", label: "Letón" },
  { code: "lt", label: "Lituano" },
  { code: "mk", label: "Macedonio" },
  { code: "ms", label: "Malayo" },
  { code: "ml", label: "Malayalam" },
  { code: "mr", label: "Maratí" },
  { code: "nl", label: "Neerlandés" },
  { code: "nl_BE", label: "Neerlandés (Bélgica)" },
  { code: "nb", label: "Noruego" },
  { code: "ps_AF", label: "Pastún" },
  { code: "fa", label: "Persa" },
  { code: "pl", label: "Polaco" },
  { code: "pt_BR", label: "Portugués (Brasil)" },
  { code: "pt_PT", label: "Portugués (Portugal)" },
  { code: "pa", label: "Panyabí" },
  { code: "ro", label: "Rumano" },
  { code: "ru", label: "Ruso" },
  { code: "sr", label: "Serbio" },
  { code: "sw", label: "Suajili" },
  { code: "sv", label: "Sueco" },
  { code: "th", label: "Tailandés" },
  { code: "ta", label: "Tamil" },
  { code: "te", label: "Telugu" },
  { code: "tr", label: "Turco" },
  { code: "uk", label: "Ucraniano" },
  { code: "ur", label: "Urdu" },
  { code: "uz", label: "Uzbeko" },
  { code: "vi", label: "Vietnamita" },
  { code: "zu", label: "Zulú" },
] as const;

export const DEFAULT_TEMPLATE_LANGUAGE = "es_CO";

const LABELS = new Map<string, string>(
  [...SPANISH_TEMPLATE_LANGUAGES, ...OTHER_TEMPLATE_LANGUAGES].map((l) => [l.code, l.label]),
);

export const TEMPLATE_LANGUAGE_CODES = [...LABELS.keys()];

/** Nombre legible del idioma; si Meta devuelve un código que no está en la lista, se muestra tal cual. */
export function templateLanguageLabel(code: string): string {
  return LABELS.get(code) ?? code;
}
